### ISSUE TITLE
Exception thrown on Go Live button

### ISSUE THREAD

**Issue by bilke** [70kft/craft-golive#7]
I am on Craft CMS 2.6.2788 and latest craft-golive. I set up everything. On pressing the `Go Live!`-button nothing happens. The control panel shows a failed task and the log outputs:

```
2016/05/26 07:46:51 [info] [application] [Forced] Starting task GoLive_Deploy that has a total of 5 steps.
2016/05/26 07:46:51 [info] [application] [Forced] Starting step 1 of 5 total steps.
2016/05/26 07:46:51 [error] [application] Encountered an error running task 1 (GoLive_Deploy), step 1 of 5: An exception was thrown: Property "Craft\GoLive_TaskService.Array" is not defined.
2016/05/26 07:46:51 [error] [exception.Craft\HttpException.404] Craft\HttpException in /var/www/craft/app/controllers/TemplatesController.php:59
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('actions/goLive/...', Array)
#1 /var/www/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /var/www/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /var/www/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /var/www/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /var/www/craft/app/etc/web/WebApp.php(288): CWebApplication->processRequest()
#9 /var/www/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /var/www/craft/app/index.php(62): CApplication->run()
#11 /var/www/public_html/index.php(25): require_once('/var/www/craft/...')
#12 {main}
REQUEST_URI=/index.php?p=admin/actions/goLive/deploy/createTask
HTTP_REFERER=http://ogs.dev/admin/golive
```

Is there anything I can try?

**Comment by eikebartels** [comment]
Hey I have the same error. Did you find a solution?
